language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - tools 
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

before_install:
 - chmod +x gradlew

before_script:
 - sudo mkdir "$ANDROID_SDK/licenses" || true
 - sudo touch "$ANDROID_SDK/licenses/android-sdk-license"
 - echo "\n8933bad161af4178b1185d1a37fbf41ea5269c55" >> "$ANDROID_SDK/licenses/android-sdk-license"

script:
   - ./gradlew build connectedCheck --stacktrace
