language: android
android:
  components:
    - tools
    - tools 
    - platform-tools
    - build-tools-24.0.2
    - android-19
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

before_install:
 - chmod +x gradlew

script:
   - ./gradlew build connectedCheck
