language: android
sudo: required
jdk: oraclejdk8
android:
  components:
    - tools
    - tools 
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

before_install:
 - android update sdk --no-ui --filter build-tools-24.0.2,android-24,extra-android-m2repository
 - chmod +x gradlew

script:
   - ./gradlew build connectedCheck --stacktrace
