# Validation : https://yaml.travis-ci.org/harmittaa/LukeApp
# http://szagurskii.com/blog/how-to-deploy-apk-to-github-releases-with-travis-ci/

language: android
sudo: required
jdk: oraclejdk8

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

env:
  global:
  - ANDROID_API_LEVEL=24
  - EMULATOR_API_LEVEL=21
  - ANDROID_BUILD_TOOLS_VERSION=24.0.2
  - ANDROID_ABI=google_apis/armeabi-v7a
  - ADB_INSTALL_TIMEOUT=20

android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-24.0.2
  - android-24
  - android-$EMULATOR_API_LEVEL
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19
  - sys-img-armeabi-v7a-addon-google_apis-google-$ANDROID_API_LEVEL
  - sys-img-armeabi-v7a-addon-google_apis-google-$EMULATOR_API_LEVEL
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
  - ".+"

before_install:
- mkdir "$ANDROID_HOME/licenses" || true
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
- chmod +x gradlew

script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"

before_script:
- echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &

# before_deploy:
# - cd LukeApp/build/outputs/apk; ls -la; md5sum *-normal-release.apk > md5sum.txt;
#  sha1sum *-normal-release.apk > sha1sum.txt; cd -

deploy:
  provider: releases
  file: LukeApp/app/build/outputs/apk/lukeapp-release.apk
  skip_cleanup: true
  on:
    repo: harmittaa/LukeApp
    tags: true
    jdk: oraclejdk8
  api_key:
    secure: Ie9y6AloQWoWwQa/tOofJveX8xbPlqyQc75X8gV6LwMrd8S3c71VhrR1VZL5cKd10JvYFZ/BPqw9JjHCkpSfqDQP7t3PCoDeqll9LEZKCCWVmpBv+Sls2xJpBAej33hAlpdJ8ig7kWOWsIHsLQdvx3NFx+tc+A4TiawZLfs4JrXqg/6SN2KJa1t7SeNZvKLE7SclXGHwXHlt8Cddznlscoffd/0yJMl+fQP1TLWLMlabNYf4zxtOAfxhl0moKru6vWYVPIY5kFL78Wpx2hftpfAWopxaKyk3M5o/OUiT5gqQpC7RMP2kw6zpLfyEsyfk0y/2roWaczWfy2xwbO1kfIaesUw6ZVu6RoIHkKxWcDWaTR85QyZhohbe372Cjt3mS56hthoJ0oja9dexZltlsMHoHVq4JcrQf2rOy45EqEZSmUwk57XaXQh0zkZp+xqK4JtN05o7HidoYMQlGnGlizbYWKuN+NclK8m9uLB9zmxhB7x+0GClxeKxTTFJZvQ8NLHtS+pObu2OfsnAvL/4EQOtqCV0jKVvS3cXezLf8zuvKuq5fl/I7OEVYxFFjFSx5JV0gycO3PV6BgeWfIsZkNvg4V874YeWdEEP/yOy0Zs57SNkVzi9uewaUJ8mKnfmuuesuyIfqvaMZia0XZshc63vL3Lp+b9IK4DmL/huO5s=

#after_success:
#- sh set_tags.sh

notifications:
  email: false
  slack:
    secure: vbkkWJ288iCxfSt2h8kT2SM0UG2qoY/LBNEZMB4AZA4vcdJIBtqzGImWnHsC4RGi0TH1pkgvtNV4SDwgBBs44IGkD7mcNkuB6liJ/kT6OP8B8KlRv6wjYMEcBSiNHYoR2BYuXVDhEoV7znh5ES2gUgy+1BJYfh/O2qh0DEBPfW9O7J5t+NbB2k1HyPMk7oTFmXs0hf+W2kwER906/Bf+bdZxM430aIEl4VWEkGoiJt2ZzIhlgQecD7KSQm/pBn3sHVqG/ZEUontl7G4P/LMSfA1K5Eg6rgjSFFNCVNMyaVa4fIutF6ARI64mBZxXkpCGJc/iqnljOy9MBgCSEVwK6iVjOrfQ2TJN4n4ohYniUN8GNW8haWQAJglWvJlPjOdQ1b+i8mEuYtkQoWs/MaK8XkKrkd0Efiw9IsMA/Y66FAG2ErdJz1+pjUL2QMZsRGY+SbyjUZlDOIxqvn4P5JxKPrBtIxWP8SCH6vH1zIxj+/mRFRky0EYjhSr3nLdcev5DvuUkvEDjVLI5jmrCNxFnRuwzSrNx/C0uy3qkeXzFBmXJYZ32PhE7G/2zWUNjK641zVDspG02LNoKmtkh3UQNn1ysAB5qzTv3pPNzmXgwHIx1LDJGOTc54684/h+yDrijiNMPgqIdbt66FrS0vwMWQqEt5toS3sbGBc3IYBeOWpc=
